### ISSUE TITLE
Rename file extension fails when extending base object with '/' in name

### ISSUE THREAD

**Issue by MikeGlue** [CloudReadySoftware/crs-al-language-extension#45]
1. Set following property:
"CRS.FileNamePatternExtensions": "<ObjectId> <BaseName>.al"

2. Create page extension for base page 14 (Salespersons/Purchasers)

3. Using the 'Rename - Current File' results in the following error:
"Running the contributed command:'crs.RenameCurrentFile' failed."

**Comment by waldo1001** [comment]
Hi @MikeGlue ,

Thanks for taking the time to file this.

I think you mean this kind of setting, right:
` "CRS.FileNamePatternExtensions": "<BaseName>.PageExt.al"`

So any kind of setting with the "BaseName" would fail because of the '.'.

This indeed results into a bug - which I'll try to fix tonight.  The scenario above, where you don't give any tag in the setting, does not result into an error on my end - but the setting is somewhat strange nevertheless ;-).

**Comment by MikeGlue** [comment]
Agggh, sorry my copy/paste failed, or I failed....I dunno…...in any case the setting I tried is actually like this:

"CRS.FileNamePatternExtensions": "<ObjectId>-<BaseName>.al"

It seems with the setting above, any base objects that contains a '/' in the object name causes the rename function to fail.

**Comment by MikeGlue** [comment]
Agggh, GitHub and it's auto-formatting text or whatever...…..…..caused my copy/paste to fail :)  

In any case, here is the actual setting I was trying: `"CRS.FileNamePatternExtensions": "<ObjectId> <BaseName>.al"`

**Comment by waldo1001** [comment]
lol - I was equally confused as the original setting.

You are right - this is a bug! Fix coming up!

**Comment by waldo1001** [comment]
Was able to replicate it in my test-function:
![image](https://user-images.githubusercontent.com/12088142/41378722-3ff5087c-6f60-11e8-8a14-29af0f90b6d6.png)

(just to brag ;-))

**Comment by waldo1001** [comment]
@MikeGlue ,

Should be fixed now.  New version is online!
I will close this issue.  If it's still there, please feel free to reopen it!

Thanks again to contribute!
