### ISSUE TITLE
When you setup Prefix it's better to add space

### ISSUE THREAD

**Issue by dkatson** [CloudReadySoftware/crs-al-language-extension#50]
Hi @waldo1001 ,
When you setup Prefix in the settings, like "CRS.ObjectNamePrefix": "AIR"
then when you run "CRC. Rename - Current file" then new name appear without space, between Prefix and object name.

For example
Before rename: table 50000 "My Super Cool Table"
After rename: table 50000 "AIRMy Super Cool Table"

I guess should be table 50000 "AIR My Super Cool Table"

Now I add extra space in setup, but this is not very beautiful)

**Comment by waldo1001** [comment]
@dkatson ,

well, it's actually intentional like that.  At least now you have the option to add a space or not.  Else, you don't ;-).

**Comment by jwikman** [comment]
@waldo1001,  I would suggest to just clarify the description of the settings CRS.ObjectNamePrefix/Suffix that you need to add a space if you want a space.

btw, I did that very same mistake by omitting the space. And since I already had the objects prefixed (with space) I didn't notice that all actions had been prefixed without space. That caused a bit more work... ;)

**Comment by waldo1001** [comment]
You are right - and sorry about that ;-).
