### ISSUE TITLE
Default AL Snippets won't disable

### ISSUE THREAD

**Issue by GreatScott000** [CloudReadySoftware/crs-al-language-extension#65]
Just installed the VSIX for NAV 2018 CU07 (0.12.25327) and now the default snippets are all enabled and try though I might I can't disable them.   I have turn the values on/off exited/reentered many times and they just won't go away.

Has something changed?

**Comment by waldo1001** [comment]
No, this is a valid issue ... 

Thing is that Microsoft works with 2 publishers, so I need to take that into account - the snippets end up in 2 different places.  I only handle one place.

Another problem is that there is no official way to disable any snippets, so what I do is I rename the snippet-folder so that the extension from MIcrosoft doesn't find them anymore.
This results into error in the background. The user is not bothered with it .. but it's not really nice.
I'm still trying to find a better way to disable snippets....  therefore this issue:https://github.com/CloudReadySoftware/crs-al-language-extension/issues/32
if you have ideas - I'm all ears ;-).

**Comment by waldo1001** [comment]
@GreatScott000 , did this new release fix it?

**Comment by GreatScott000** [comment]
I am not sure.  The default snippets do not appear but I get a message the a message about the Snippets folder is not found.

![image](https://user-images.githubusercontent.com/4333956/42698409-b6d02f6e-86b5-11e8-912b-82815224f397.png)

**Comment by waldo1001** [comment]
@GreatScott000 ,
next version, this should be fixed (let's hope ;-))
