### ISSUE TITLE
Reorganize files does not work with multi folder workspaces

### ISSUE THREAD

**Issue by fvet** [CloudReadySoftware/crs-al-language-extension#7]
Having created 2 dummy extensions in separate folders and added both in one VS workspace, I tried using the 'CRS Reorganize - All Files' afterwards, but apparently it moved files from my second 'Master Data' folder into my first extension 'Base' folder.  Files should not be moved accross folders within the same Workspace.

![screenshot_3](https://user-images.githubusercontent.com/25268332/37935760-0699b262-3153-11e8-9838-dc22642f6036.jpg)

**Comment by waldo1001** [comment]
Multip folder workspace - that's something I'll need to dive into at a later point, because it breaks my functionality, indeed.  It's quite recent in VSCode as well.. .

Just for my own notes:
I have a few touchpoints - I work with "workspace.rootPath", which doesn't work for multifolder-workspaces.  I need to go with workspace.workspacefolder and/or workspace.getWorkspaceFolder, although, then I need to give my "getSetttings" a context, where I wasn't.

Is this an urgent request?  I never work with this option :-).

As a temporary workaround, you could just work as single workspace - then reorganize - then open multi again..

**Comment by fvet** [comment]
Not that urgent, since the workaround does the job ;)
